version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    command: flask --app app/main.py run --host=0.0.0.0 -p 8080

  worker:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    command: python worker.py
